name: Create MSSQL container
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -x
        . /etc/os-release
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor --batch --yes -o /usr/share/keyrings/microsoft-prod.gpg
        curl https://packages.microsoft.com/config/ubuntu/$VERSION_ID/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
        sudo apt-get update -y
        sudo ACCEPT_EULA=Y apt-get install -y unixodbc msodbcsql18
        docker run \
          -e "ACCEPT_EULA=Y" \
          -e "SA_PASSWORD=<YourStrong@Passw0rd>" \
          -p 1433:1433 \
          --name sql1 \
          -h sql1 \
          -d mcr.microsoft.com/mssql/server:2022-CU14-ubuntu-22.04
