name: Test
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  WINDOWS:
    name: C11 and noreturn
    uses: ./.github/workflows/test-suite.yml
    with:
      all_variations: false
      branch: >-
        {"name":"C11 and noreturn","ref":"${{ github.ref }}","version":[8,7],"jobs":{"WINDOWS":{"matrix":{"include":[{"x64":true,"zts":true,"asan":false,"clang":false,"opcache":true,"serial":false},{"x64":true,"zts":false,"asan":false,"clang":false,"opcache":true,"serial":true},{"x64":true,"zts":true,"asan":false,"clang":true,"opcache":true,"serial":false}]},"config":{"vs_crt_version":"vs18","runs_on":"windows-2025-vs2026"}}},"config":{"default_run_test_jobs":"","integrated_opcache":true}}
    secrets: inherit
